services:
  _defaults:
    public: true


  prestashop.module.pga.repository:
    class: Respawnsive\Pga\Repository\PgaRepository
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $languages: '@=service("prestashop.adapter.legacy.context").getLanguages(false, service("prestashop.adapter.shop.context").getContextShopID())'
      $translator: '@translator'
      $isMultiStoreUsed: '@=service("prestashop.adapter.feature.multistore").isUsed()'
      $multiStoreContext: '@prestashop.adapter.shop.context'

  Respawnsive\Pga\Form\Modifier\ProductFormModifier:
    autowire: true
    public: true
    arguments:
        - '@form.form_builder_modifier'
        - '@=service("prestashop.core.form.choice_provider.group_by_id").getChoices()'
